[package]
name = "starter"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1

[dependencies.wavesabre-rs]
git = 'https://github.com/Kwarf/wavesabre-rs.git'

[dependencies.windows-sys]
version = '0.42.0'
default-features = false
features = [
    'Win32_Foundation',
    'Win32_Graphics_Gdi',
    'Win32_Graphics_OpenGL',
    'Win32_System_Performance',
    'Win32_System_Threading',
    'Win32_UI_Input_KeyboardAndMouse',
    'Win32_UI_WindowsAndMessaging',
]
